=== lucifron28/OpenIT-Bootcamp/Day-1/activities/librarybookschema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["id", "title", "authors", "published_year", "available", "genres", "publisher"],
    "properties": {
        "id": {
            "type": "integer",
            "minimum": 1
        },
        "title": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string",
                "minLength": 1,
                "maxLength": 255
            }
        },
        "published_year": {
            "type": "integer",
            "minimum": 1000,
            "maximum": 2026
        },
        "available": {
            "type": "boolean"
        },
        "genres": {
            "type": "array",
            "minItems": 2,
            "items": {
                "type": "string"
            }
        },
        "publisher": {
            "type": "object",
            "required": ["name", "city"],
            "properties": {
                "name": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                }
            }
        }
    }
}

=== lucifron28/OpenIT-Bootcamp/Day-1/activities/librarybook.json
{
    "id": 1,
    "title": "Wuthering Heights",
    "authors": ["Emily Brontë"],
    "published_year": 1847,
    "available": true,
    "genres": ["Gothic Fiction", "Romance", "Revege Tragedy", "Victorian Realism"],
    "publisher": {
        "name" : "Penguin Classics",
        "city": "New York, USA"
    }
}
